version: '3'
services:
  db:
    build: containers/postgres
    ports:
      - "3001:5432"
    volumes:
      - "/var/lib/postgresql/data"

  repl:
    build: .
    command: lein repl
    ports:
      - "3000:3000"
      - "39998:39998"
    depends_on:
      - db
    volumes:
      - ".:/todo"
      - "lib_data:/root/.m2/repository"
    environment:
      - DEV_DB_URL=jdbc:postgresql://db:5432/todo-development?user=postgres&password=
      - TEST_DB_URL=jdbc:postgresql://db:5432/todo-test?user=postgres&password=
      - JWT_SECRET=maGxR3fMrnfmAdBEDJAoU59ggB+9+/d3V8yq+xKRAmZ1F5BknJAzET1qxv+G/Eqm

volumes:
  lib_data:
